package gap.com.driver.database.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.io.Serializable;

/**
 * Entity mapped to table "DRIVER".
 */

@Entity
public class Driver implements Serializable {

    @PrimaryKey()
    private Long id;
    @ColumnInfo(name = "driverId")
    private Long driverId;
    @ColumnInfo(name = "serverUserId")
    private Integer serverUserId;
    @ColumnInfo(name = "name")
    private String name;
    @ColumnInfo(name = "family")
    private String family;
    @ColumnInfo(name = "mobileNo")
    private String mobileNo;
    @ColumnInfo(name = "username")
    private String username;
    @ColumnInfo(name = "password")
    private String password;
    @ColumnInfo(name = "companyName")
    private String companyName;
    @ColumnInfo(name = "picturePathUrl")
    private String picturePathUrl;
    @ColumnInfo(name = "expireDate")
    private String expireDate;
    @ColumnInfo(name = "lastLoginDate")
    private String lastLoginDate;
    @ColumnInfo(name = "loginStatus")
    private Integer loginStatus;
    @ColumnInfo(name = "autoLogin")
    private Boolean autoLogin;
    @ColumnInfo(name = "loginIs")
    private Boolean loginIs;
    @ColumnInfo(name = "alreadyRegistered")
    private Boolean alreadyRegistered;
    @ColumnInfo(name = "driverCode")
    private Integer driverCode;

    public Driver() {
    }


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getDriverId() {
        return driverId;
    }

    public void setDriverId(Long driverId) {
        this.driverId = driverId;
    }

    public Integer getServerUserId() {
        return serverUserId;
    }

    public void setServerUserId(Integer serverUserId) {
        this.serverUserId = serverUserId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFamily() {
        return family;
    }

    public void setFamily(String family) {
        this.family = family;
    }

    public String getMobileNo() {
        return mobileNo;
    }

    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getPicturePathUrl() {
        return picturePathUrl;
    }

    public void setPicturePathUrl(String picturePathUrl) {
        this.picturePathUrl = picturePathUrl;
    }

    public String getExpireDate() {
        return expireDate;
    }

    public void setExpireDate(String expireDate) {
        this.expireDate = expireDate;
    }

    public String getLastLoginDate() {
        return lastLoginDate;
    }

    public void setLastLoginDate(String lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    public Integer getLoginStatus() {
        return loginStatus;
    }

    public void setLoginStatus(Integer loginStatus) {
        this.loginStatus = loginStatus;
    }

    public Boolean getAutoLogin() {
        return autoLogin;
    }

    public void setAutoLogin(Boolean autoLogin) {
        this.autoLogin = autoLogin;
    }

    public Boolean getLoginIs() {
        return loginIs;
    }

    public void setLoginIs(Boolean loginIs) {
        this.loginIs = loginIs;
    }

    public Boolean getAlreadyRegistered() {
        return alreadyRegistered;
    }

    public void setAlreadyRegistered(Boolean alreadyRegistered) {
        this.alreadyRegistered = alreadyRegistered;
    }

    public Integer getDriverCode() {
        return driverCode;
    }

    public void setDriverCode(Integer driverCode) {
        this.driverCode = driverCode;
    }
}
